const 博客_建站={
    text:'博主&建站',
    children:[
        {
            text:'博主',
            children:[
                {
                    text:'Jitwxs',
                    link:'https://jitwxs.cn'
                },
                {
                    text:'架构师',
                    link:'https://www.mobaijun.com'
                },
                {
                    text:'友人c',
                    link:'https://www.ihewro.com'
                },
                {
                    text:'哈喽',
                    link:'https://www.cnblogs.com/hahaha111122222'
                },
                {
                    text:'日拱一兵',
                    link:'https://dayarch.top/'
                },
                {
                    text:'ArcherGu',
                    link:'https://archergu.me/posts'
                },
                {
                    text:'阿虚同学',
                    link:'https://axutongxue.com/'
                },
                {
                    text:'骏马金龙',
                    link:'https://www.junmajinlong.com'
                },
                {
                    text:'小弋の生活馆',
                    link:'https://lovelijunyi.gitee.io/'
                },
                {
                    text:'java全栈知识体系',
                    link:'https://pdai.tech'
                },
                {
                    text:'huskyAreYouScared-Blog',
                    link:'https://huskyareyouscared.github.io/blog/'
                },
            ]
        },
        {
            text:'建站',
            children:[
                {
                    text:'hexo',
                    link:'https://hexo.io/zh-cn/index.html'
                },
                {
                    text:'vuepress',
                    link:'https://v2.vuepress.vuejs.org/zh/'
                },
                {
                    text:'halo',
                    link:'https://halo.run'
                },
                {
                    text:'astro',
                    link:'https://docs.astro.build/zh-cn/getting-started/'
                },
            ]
        }
    ]
}

export default 博客_建站